### ISSUE TITLE
Doesn't seem to work with Enumeratum

### ISSUE THREAD

**Issue by guizmaii** [circe/circe-golden#40]
Hi Travis,

Here's an example to reproduce the problem:

```scala
package com.example

import cats.Eq
import enumeratum.{CirceEnum, Enum, EnumEntry}
import enumeratum.EnumEntry.Uppercase
import io.circe.Codec
import io.circe.generic.semiauto._
import io.circe.testing.ArbitraryInstances
import io.circe.testing.golden.GoldenCodecTests
import org.scalacheck.{Arbitrary, Gen}
import org.scalacheck.Arbitrary.arbitrary
import org.scalatest.flatspec.AnyFlatSpec
import org.scalatest.prop.Configuration
import org.typelevel.discipline.scalatest.FlatSpecDiscipline

object CurrencyGoldenTest {
  sealed abstract class Currency extends EnumEntry
  object Currency extends Enum[Currency] with Uppercase with CirceEnum[Currency] {
    override final val values = findValues

    final case object AUD extends Currency
  }

  final case class Price(value: Double, currency: Currency)
  object Price {
    implicit final val codec: Codec[Price] = deriveCodec
  }

  implicit val arbCurrency: Arbitrary[Currency] = Arbitrary(Gen.oneOf(Currency.values))
  implicit val arbPrice: Arbitrary[Price] = Arbitrary {
    for {
      v <- arbitrary[Double]
      c <- arbitrary[Currency]
    } yield Price(value = v, currency = c)
  }
}

class CurrencyGoldenTest extends AnyFlatSpec with FlatSpecDiscipline with Configuration with ArbitraryInstances {

  import CurrencyGoldenTest._

  implicit final val eqCurrency: Eq[Currency] = Eq.fromUniversalEquals
  implicit final val eqPrice: Eq[Price]       = Eq.fromUniversalEquals

  checkAll("GoldenCodec[Currency]", GoldenCodecTests[Currency].goldenCodec)
  checkAll("GoldenCodec[Price]", GoldenCodecTests[Price].goldenCodec)

}
```

When I run it, I have the following error:

```scala
NotSerializableException was thrown during property evaluation.
  Message: com.example.CurrencyGoldenTest$Currency$
  Occurred when passed generated values (

  )
ScalaTestFailureLocation: org.scalatestplus.scalacheck.CheckerAsserting$$anon$2 at (CurrencyGoldenTest.scala:45)
org.scalatest.exceptions.GeneratorDrivenPropertyCheckFailedException: NotSerializableException was thrown during property evaluation.
  Message: com.example.CurrencyGoldenTest$Currency$
  Occurred when passed generated values (

  )
	at org.scalatestplus.scalacheck.CheckerAsserting$$anon$2.indicateFailure(CheckerAsserting.scala:251)
	at org.scalatestplus.scalacheck.CheckerAsserting$$anon$2.indicateFailure(CheckerAsserting.scala:238)
	at org.scalatestplus.scalacheck.UnitCheckerAsserting$CheckerAssertingImpl.check(CheckerAsserting.scala:160)
 ...
```

I've added a breakpoint on the `GeneratorDrivenPropertyCheckFailedException` exception, and we can find the following message in the `pos` parameter of this type:

```scala
Please set the environment variable SCALACTIC_FILL_FILE_PATHNAMES to yes at compile time to enable this feature.
``` 

Any idea of how to mitigate that problem and/or where it can come from?

Thanks,
Jules

**Comment by travisbrown** [comment]
@guizmaii Can you try `GoldenCodecTests[X].unserializableGoldenCodec` instead of `.goldenCodec`?

By default the circe-testing laws (which circe-golden wraps) include a check that the codecs are serializable. `unserializableCodec` / `unserializableGoldenCodec` are the standard ways to run all checks except that one.

**Comment by guizmaii** [comment]
Works perfectly fine.

Thanks a lot, Travis :)
